[2024-10-07T00:23:29.952+0000] {processor.py:186} INFO - Started process (PID=1533) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:23:29.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:23:29.965+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:23:29.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:23:29.992+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:23:29.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:23:30.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:23:30.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.115 seconds
[2024-10-07T00:24:00.332+0000] {processor.py:186} INFO - Started process (PID=1549) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:24:00.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:24:00.335+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:00.335+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:24:00.351+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:00.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:24:00.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:24:00.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-07T00:24:30.600+0000] {processor.py:186} INFO - Started process (PID=1565) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:24:30.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:24:30.602+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:30.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:24:30.611+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:24:30.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:24:30.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:24:30.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.029 seconds
[2024-10-07T00:33:12.919+0000] {processor.py:186} INFO - Started process (PID=1581) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:33:12.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:33:12.922+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:12.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:33:12.935+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:12.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:33:12.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:33:12.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-07T00:33:43.164+0000] {processor.py:186} INFO - Started process (PID=1597) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:33:43.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:33:43.168+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:43.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:33:43.185+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:33:43.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:33:43.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:33:43.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-10-07T00:34:13.466+0000] {processor.py:186} INFO - Started process (PID=1613) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:34:13.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:34:13.469+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:13.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:34:13.483+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:13.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:34:13.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:34:13.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-07T00:34:43.754+0000] {processor.py:186} INFO - Started process (PID=1629) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:34:43.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:34:43.758+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:43.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:34:43.774+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:34:43.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:34:43.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:34:43.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-07T00:35:14.049+0000] {processor.py:186} INFO - Started process (PID=1645) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:35:14.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:35:14.052+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:14.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:35:14.069+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:14.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:35:14.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:35:14.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-10-07T00:35:44.334+0000] {processor.py:186} INFO - Started process (PID=1661) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:35:44.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:35:44.337+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:44.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:35:44.352+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:35:44.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:35:44.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:35:44.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-07T00:36:14.652+0000] {processor.py:186} INFO - Started process (PID=1677) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:36:14.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:36:14.656+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:14.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:36:14.671+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:14.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:36:14.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:36:14.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-07T00:36:44.959+0000] {processor.py:186} INFO - Started process (PID=1693) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:36:44.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:36:44.962+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:44.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:36:44.976+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:36:44.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:36:44.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:36:44.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-07T00:37:15.262+0000] {processor.py:186} INFO - Started process (PID=1709) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:37:15.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:37:15.266+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:15.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:37:15.287+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:15.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:37:15.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:37:15.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.054 seconds
[2024-10-07T00:37:45.566+0000] {processor.py:186} INFO - Started process (PID=1725) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:37:45.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:37:45.576+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:45.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:37:45.594+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:37:45.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:37:45.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:37:45.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.057 seconds
[2024-10-07T00:38:15.853+0000] {processor.py:186} INFO - Started process (PID=1741) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:38:15.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:38:15.856+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:15.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:38:15.875+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:15.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:38:15.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:38:15.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-07T00:38:46.159+0000] {processor.py:186} INFO - Started process (PID=1757) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:38:46.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:38:46.162+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:46.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:38:46.177+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:38:46.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:38:46.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:38:46.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-07T00:39:16.464+0000] {processor.py:186} INFO - Started process (PID=1773) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:39:16.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:39:16.467+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:16.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:39:16.481+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:16.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:39:16.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:39:16.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-07T00:39:46.759+0000] {processor.py:186} INFO - Started process (PID=1789) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:39:46.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:39:46.763+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:46.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:39:46.782+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:39:46.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:39:46.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:39:46.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.057 seconds
[2024-10-07T00:40:17.070+0000] {processor.py:186} INFO - Started process (PID=1805) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:40:17.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:40:17.074+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:17.073+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:40:17.087+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:17.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:40:17.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:40:17.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-07T00:40:47.360+0000] {processor.py:186} INFO - Started process (PID=1821) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:40:47.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:40:47.364+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:47.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:40:47.379+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:40:47.378+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:40:47.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:40:47.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-07T00:41:17.668+0000] {processor.py:186} INFO - Started process (PID=1837) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:41:17.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:41:17.671+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:17.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:41:17.688+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:17.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:41:17.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:41:17.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-07T00:41:47.965+0000] {processor.py:186} INFO - Started process (PID=1853) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:41:47.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:41:47.968+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:47.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:41:47.986+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:41:47.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:41:47.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:41:48.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-10-07T00:42:18.255+0000] {processor.py:186} INFO - Started process (PID=1869) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:42:18.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:42:18.258+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:18.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:42:18.273+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:18.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:42:18.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:42:18.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-07T00:42:48.547+0000] {processor.py:186} INFO - Started process (PID=1885) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:42:48.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:42:48.550+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:48.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:42:48.565+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:42:48.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:42:48.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:42:48.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:43:18.888+0000] {processor.py:186} INFO - Started process (PID=1901) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:43:18.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:43:18.891+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:18.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:43:18.910+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:18.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:43:18.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:43:18.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-10-07T00:43:49.197+0000] {processor.py:186} INFO - Started process (PID=1917) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:43:49.198+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:43:49.201+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:49.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:43:49.215+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:43:49.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:43:49.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:43:49.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-07T00:44:19.491+0000] {processor.py:186} INFO - Started process (PID=1933) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:44:19.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:44:19.494+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:19.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:44:19.509+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:19.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:44:19.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:44:19.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:44:49.787+0000] {processor.py:186} INFO - Started process (PID=1949) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:44:49.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:44:49.790+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:49.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:44:49.806+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:44:49.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:44:49.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:44:49.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.052 seconds
[2024-10-07T00:45:20.013+0000] {processor.py:186} INFO - Started process (PID=1965) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:45:20.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:45:20.022+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:20.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:45:20.037+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:20.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:45:20.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:45:20.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-10-07T00:45:50.263+0000] {processor.py:186} INFO - Started process (PID=1981) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:45:50.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:45:50.266+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:50.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:45:50.280+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:45:50.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:45:50.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:45:50.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-10-07T00:46:20.555+0000] {processor.py:186} INFO - Started process (PID=1997) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:46:20.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:46:20.557+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:20.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:46:20.572+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:20.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:46:20.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:46:20.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-07T00:46:50.842+0000] {processor.py:186} INFO - Started process (PID=2013) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:46:50.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:46:50.845+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:50.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:46:50.859+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:46:50.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:46:50.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:46:50.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.039 seconds
[2024-10-07T00:47:21.144+0000] {processor.py:186} INFO - Started process (PID=2029) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:47:21.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:47:21.148+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:21.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:47:21.164+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:21.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:47:21.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:47:21.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.051 seconds
[2024-10-07T00:47:51.431+0000] {processor.py:186} INFO - Started process (PID=2045) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:47:51.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:47:51.435+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:51.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:47:51.450+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:47:51.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:47:51.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:47:51.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-10-07T00:48:21.756+0000] {processor.py:186} INFO - Started process (PID=2061) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:48:21.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:48:21.759+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:21.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:48:21.774+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:21.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:48:21.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:48:21.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:48:52.046+0000] {processor.py:186} INFO - Started process (PID=2077) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:48:52.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:48:52.050+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:52.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:48:52.062+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:48:52.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:48:52.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:48:52.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-07T00:49:22.339+0000] {processor.py:186} INFO - Started process (PID=2093) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:49:22.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:49:22.342+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:22.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:49:22.357+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:22.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:49:22.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:49:22.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:49:52.619+0000] {processor.py:186} INFO - Started process (PID=2109) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:49:52.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:49:52.622+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:52.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:49:52.635+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:49:52.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:49:52.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:49:52.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.035 seconds
[2024-10-07T00:50:22.900+0000] {processor.py:186} INFO - Started process (PID=2125) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:50:22.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:50:22.904+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:22.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:50:22.917+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:22.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:50:22.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:50:22.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.053 seconds
[2024-10-07T00:50:53.142+0000] {processor.py:186} INFO - Started process (PID=2141) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:50:53.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:50:53.146+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:53.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:50:53.163+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:50:53.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:50:53.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:50:53.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.048 seconds
[2024-10-07T00:51:23.440+0000] {processor.py:186} INFO - Started process (PID=2157) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:51:23.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:51:23.448+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:23.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:51:23.463+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:23.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:51:23.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:51:23.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.135 seconds
[2024-10-07T00:51:53.821+0000] {processor.py:186} INFO - Started process (PID=2173) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:51:53.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:51:53.823+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:53.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:51:53.839+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:51:53.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:51:53.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:51:53.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.055 seconds
[2024-10-07T00:52:24.121+0000] {processor.py:186} INFO - Started process (PID=2189) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:52:24.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:52:24.124+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:24.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:52:24.141+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:24.139+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:52:24.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:52:24.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-10-07T00:52:54.411+0000] {processor.py:186} INFO - Started process (PID=2205) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:52:54.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:52:54.415+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:54.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:52:54.431+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:52:54.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:52:54.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:52:54.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-07T00:53:24.728+0000] {processor.py:186} INFO - Started process (PID=2221) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:53:24.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:53:24.731+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:24.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:53:24.746+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:24.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:53:24.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:53:24.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:53:55.025+0000] {processor.py:186} INFO - Started process (PID=2237) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:53:55.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:53:55.029+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:55.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:53:55.047+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:53:55.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:53:55.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:53:55.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-10-07T00:54:25.309+0000] {processor.py:186} INFO - Started process (PID=2253) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:54:25.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:54:25.312+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:25.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:54:25.325+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:25.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:54:25.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:54:25.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:54:55.577+0000] {processor.py:186} INFO - Started process (PID=2269) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:54:55.578+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:54:55.580+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:55.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:54:55.594+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:54:55.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:54:55.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:54:55.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-10-07T00:55:25.859+0000] {processor.py:186} INFO - Started process (PID=2285) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:55:25.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:55:25.862+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:25.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:55:25.875+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:25.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:55:25.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:55:25.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-07T00:55:56.151+0000] {processor.py:186} INFO - Started process (PID=2301) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:55:56.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:55:56.154+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:56.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:55:56.167+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:55:56.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:55:56.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:55:56.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-07T00:56:26.428+0000] {processor.py:186} INFO - Started process (PID=2318) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:56:26.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:56:26.431+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:26.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:56:26.445+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:26.443+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:56:26.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:56:26.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-10-07T00:56:56.704+0000] {processor.py:186} INFO - Started process (PID=2334) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:56:56.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:56:56.708+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:56.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:56:56.722+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:56:56.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:56:56.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:56:56.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-07T00:57:26.979+0000] {processor.py:186} INFO - Started process (PID=2350) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:57:26.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:57:26.982+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:26.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:57:26.996+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:26.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:57:26.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:57:27.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.038 seconds
[2024-10-07T00:57:57.257+0000] {processor.py:186} INFO - Started process (PID=2366) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:57:57.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:57:57.259+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:57.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:57:57.274+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:57:57.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:57:57.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:57:57.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-10-07T00:58:27.587+0000] {processor.py:186} INFO - Started process (PID=2382) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:58:27.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:58:27.591+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:27.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:58:27.612+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:27.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:58:27.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:58:27.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.052 seconds
[2024-10-07T00:58:57.879+0000] {processor.py:186} INFO - Started process (PID=2398) to work on /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:58:57.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-10-07T00:58:57.881+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:57.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:58:57.896+0000] {logging_mixin.py:190} INFO - [2024-10-07T00:58:57.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 47
    task_id='get_age'
            ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-10-07T00:58:57.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-10-07T00:58:57.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
